version: '3.8'

x-client-env: &client-env
  CLIENT_MODE: auto
  SERVER_HOST: mafia_server
  SERVER_PORT: 9000
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  RABBITMQ_HOSTNAME: rabbitmq
  RABBITMQ_PORT: 5672

services:
  server:
    image: fdr400/soa_mafia_driver_server
    hostname: "mafia_server"
    ports:
      - 9000:9000/tcp
    environment:
      - PORT=9000
      - SESSION_PLAYERS=4
      - MAFIAS=1
    depends_on:
      - rabbitmq
    restart: on-failure

  bot1:
    image: fdr400/soa_mafia_driver_client
    environment:
      USERNAME: bot1
      <<: *client-env
    depends_on:
      - server
    restart: always

  bot2:
    image: fdr400/soa_mafia_driver_client
    environment:
      USERNAME: bot2
      <<: *client-env
    depends_on:
      - server
    restart: always

  bot3:
    image: fdr400/soa_mafia_driver_client
    environment:
      USERNAME: bot3
      <<: *client-env
    depends_on:
      - server
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

