version: '1.0'

services:
  server:
    image: fdr400/soa_mafia_driver_server
    hostname: "mafia_server"
    ports:
      - 9000:9000/tcp
    environment:
      - PORT=9000
      - SESSION_PLAYERS=4

  bot1:
    image: fdr400/soa_mafia_driver_client:latest
    environment:
      - CLIENT_MODE=auto
      - SERVER_HOST=mafia_server
      - SERVER_PORT=9000
      - USERNAME=bot1
    depends_on:
      - server

  bot2:
    image: fdr400/soa_mafia_driver_client:latest
    environment:
      - CLIENT_MODE=auto
      - SERVER_HOST=mafia_server
      - SERVER_PORT=9000
      - USERNAME=bot2
    depends_on:
      - server

  bot3:
    image: fdr400/soa_mafia_driver_client:latest
    environment:
      - CLIENT_MODE=auto
      - SERVER_HOST=mafia_server
      - SERVER_PORT=9000
      - USERNAME=bot3
    depends_on:
      - server
